import { AddPayment, Payment } from '../models';

export const INITIAL_ADD_DATA: AddPayment[] = [
  {
    paymentName: 'Интернет',
    pricePerDay: '20',
  },
  {
    paymentName: 'Домашний телефон',
    pricePerDay: '15',
  },
  {
    paymentName: 'Мобильный телефон',
    pricePerDay: '30',
  },
  {
    paymentName: 'IPTV',
    pricePerDay: '20',
  },
  {
    paymentName: 'Подписка на музыку',
    pricePerDay: '15',
  },
  {
    paymentName: 'Подписка на фильмы',
    pricePerDay: '15',
  },
  {
    paymentName: 'Абонемент на фитнес',
    pricePerDay: '100',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 0,
    paymentName: 'Интернет',
    months: {
      january: true,
      february: true,
      march: false,
      april: false,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    pricePerDay: 20,
    lastChangesDate: new Date(),
  },
  {
    id: 1,
    paymentName: 'Домашний телефон',
    months: {
      january: false,
      february: false,
      march: false,
      april: false,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    pricePerDay: 15,
    lastChangesDate: new Date(),
  },
  {
    id: 2,
    paymentName: 'Мобильный телефон',
    months: {
      january: true,
      february: true,
      march: true,
      april: false,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    pricePerDay: 30,
    lastChangesDate: new Date(),
  },
  {
    id: 3,
    paymentName: 'IPTV',
    months: {
      january: false,
      february: false,
      march: true,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    pricePerDay: 20,
    lastChangesDate: new Date(),
  },
  {
    id: 4,
    paymentName: 'Подписка на музыку',
    months: {
      january: false,
      february: false,
      march: true,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    pricePerDay: 15,
    lastChangesDate: new Date(),
  },
  {
    id: 5,
    paymentName: 'Подписка на фильмы',
    months: {
      january: false,
      february: false,
      march: true,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    pricePerDay: 15,
    lastChangesDate: new Date(),
  },
  {
    id: 6,
    paymentName: 'Абонемент на фитнес',
    months: {
      january: false,
      february: false,
      march: false,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    pricePerDay: 100,
    lastChangesDate: new Date(),
  }
];
