import { AddPayment, Payment } from '../models';

export const INITIAL_ADD_DATA: AddPayment[] = [
    {
        paymentName: 'Интернет',
        price: '600',
    },
    {
        paymentName: 'Домашний телефон',
        price: '500',
    },
    {
        paymentName: 'Мобильный телефон',
        price: '300',
    },
    {
        paymentName: 'IPTV',
        price: '200',
    },
    {
        paymentName: 'Подписка на музыку',
        price: '150',
    },
    {
        paymentName: 'Подписка на фильмы',
        price: '150',
    },
    {
        paymentName: 'Абонемент на фитнес',
        price: '1000',
    },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 0,
    paymentName: 'Интернет',
    months: {
      january: true,
      february: true,
      march: false,
      april: false,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    price: 600,
    lastChangesDate: new Date(),
  },
  {
    id: 1,
    paymentName: 'Домашний телефон',
    months: {
      january: false,
      february: false,
      march: false,
      april: false,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    price: 500,
    lastChangesDate: new Date(),
  },
  {
    id: 2,
    paymentName: 'Мобильный телефон',
    months: {
      january: true,
      february: true,
      march: true,
      april: false,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    price: 300,
    lastChangesDate: new Date(),
  },
  {
    id: 3,
    paymentName: 'IPTV',
    months: {
      january: false,
      february: false,
      march: true,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    price: 200,
    lastChangesDate: new Date(),
  },
  {
    id: 4,
    paymentName: 'Подписка на музыку',
    months: {
      january: false,
      february: false,
      march: true,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    price: 150,
    lastChangesDate: new Date(),
  },
  {
    id: 5,
    paymentName: 'Подписка на фильмы',
    months: {
      january: false,
      february: false,
      march: true,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    price: 150,
    lastChangesDate: new Date(),
  },
  {
    id: 6,
    paymentName: 'Абонемент на фитнес',
    months: {
      january: false,
      february: false,
      march: false,
      april: true,
      may: false,
      june: false,
      july: false,
      august: false,
      september: false,
      october: false,
      november: false,
      december: false,
    },
    price: 1000,
    lastChangesDate: new Date(),
  }
];
